import { readFileSync } from "fs";
import { ServiceAccount } from "firebase-admin";
import { cert, initializeApp } from "firebase-admin/app";

/*
    Initialize the Firebase Admin SDK using a Service Account.

    - Read the serviceAccountKey.json file generated by Firebase.
    - Convert its contents into a JavaScript object.
    - Use the credentials to authenticate this script with Firebase.

    This allows the script to perform privileged operations such as
    seeding Firestore, managing Authentication, or other admin tasks.

    Note:
    The "as ServiceAccount" assertion is only for TypeScript. It tells
    the compiler that the parsed JSON matches the expected ServiceAccount
    type and does not change the object at runtime.
*/
const serviceAccount = JSON.parse(
    readFileSync("./serviceAccountKey.json", "utf8")
) as ServiceAccount;

initializeApp({
    credential: cert(serviceAccount),
});