import { ServiceAccount } from "firebase-admin";
import { cert, initializeApp } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { readFileSync } from "fs";

/*
    Initialize the Firebase Admin SDK using a Service Account.

    - Read the serviceAccountKey.json file generated by Firebase.
    - Convert its contents into a JavaScript object.
    - Use the credentials to authenticate this script with Firebase.

    This allows the script to perform privileged operations such as
    seeding Firestore, managing Authentication, or other admin tasks.
*/
const serviceAccount = JSON.parse(
    readFileSync("./serviceAccountKey.json", "utf8")
) as ServiceAccount;

const app = initializeApp({
    credential: cert(serviceAccount),
});

// Export Firestore so other files can use it
export const db = getFirestore(app);