// ⚠️❗AUTO-GENERATED FILE. DO NOT EDIT. PLEASE!!! -JEM 

export const plantImages: Record<string, any> = {
  "cassia-alata": require("@images/plants/Akapulko.jpg"),
  "aloe-vera": require("@images/plants/Aloe Vera.jpg"),
  "momordica-charantia": require("@images/plants/Ampalaya.jpg"),
  "musa-paradisiaca": require("@images/plants/Banana.jpg"),
  "allium-sativum": require("@images/plants/Bawang.jpg"),
  "psidium-guajava": require("@images/plants/Bayabas.jpg"),
  "piper-betle": require("@images/plants/Betel Leaf.jpg"),
  "citrus-aurantifolia": require("@images/plants/Calamansi.jpg"),
  "cocos-nucifera": require("@images/plants/Coconut.jpg"),
  "murraya-koenigii": require("@images/plants/Curry Leaf.jpg"),
  "syzygium-cumini": require("@images/plants/Duhat.jpg"),
  "eucalyptus-globulus": require("@images/plants/Eucalyptus.jpg"),
  "zingiber-officinale": require("@images/plants/Ginger.jpg"),
  "centella-asiatica": require("@images/plants/Gotu Kola.jpg"),
  "camellia-sinensis": require("@images/plants/Green Tea.jpg"),
  "tinospora-cordifolia": require("@images/plants/Guduchi.jpg"),
  "hibiscus-rosa-sinensis": require("@images/plants/Gumamela.jpg"),
  "annona-muricata": require("@images/plants/Guyabano.jpg"),
  "lawsonia-inermis": require("@images/plants/Henna.jpg"),
  "ocimum-tenuiflorum": require("@images/plants/Holy Basil.jpg"),
  "andrographis-paniculata": require("@images/plants/King of Bitters.jpg"),
  "vitex-negundo": require("@images/plants/lagundi.jpg"),
  "citrus-limon": require("@images/plants/Lemon.jpg"),
  "mimosa-pudica": require("@images/plants/Makahiya.jpg"),
  "moringa-oleifera": require("@images/plants/Malunggay.jpg"),
  "mangifera-indica": require("@images/plants/Mango.jpg"),
  "artemisia-vulgaris": require("@images/plants/Mugwort.jpg"),
  "azadirachta-indica": require("@images/plants/Neem.jpg"),
  "quisqualis-indica": require("@images/plants/Niyog-Niyogan.jpg"),
  "carica-papaya": require("@images/plants/Papaya.jpg"),
  "mentha-piperita": require("@images/plants/Peppermint.jpg"),
  "punica-granatum": require("@images/plants/Pomegranate.jpg"),
  "blumea-balsamifera": require("@images/plants/Sambong.jpg"),
  "phyllanthus-niruri": require("@images/plants/Stonebreaker.jpg"),
  "ocimum-basilicum": require("@images/plants/Sweet Basil.jpg"),
  "cymbopogon-citratus": require("@images/plants/Tanglad.jpg"),
  "ehretia-microphylla": require("@images/plants/Tsaang Gubat.jpg"),
  "curcuma-longa": require("@images/plants/Turmeric.jpg"),
  "peperomia-pellucida": require("@images/plants/Ulasimang Bato.jpg"),
  "clinopodium-douglasii": require("@images/plants/Yerba Buena.jpg"),
};
